.TH man 3 "14 November 2016" "[...] man page"
.SH NAME
ezforeach -\ applies function to for each array index
.SH PROTOTYPE
void ezforeach(ARRAY array, EZCALLBACK)
.SH DESCRIPTION
Applies the specified function to each array index.
.P
EZCALLBACK being a define of void (*callback)(void *)
.SH OPTIONS
None.
.SH KNOWN ISSUES
None.
.SH SEEL ALSO
.BR ezarray_get_index (3)
.SH AUTHOR
PINCHON Guillaume (gpinchon@student.42.fr)